### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by iAmHuss** [ngreenwald89/gin_rummy#14]
must create an audit trail of every game move, and these game moves must not be available to those not in the game until the game has completed. After the game is completed, the final audit record (including every move) must be publicly available to all authenticated users (but to not to unauthenticated ones). The win/loss/draw record of each user must be made available to authenticated users (but not to unauthenticated ones).

**Comment by ngreenwald89** [comment]
GameLog

game_id: models.ForeignKey(RummyGame)
turn_id: models.ForeignKey(RummyPlayer.username)
draw_option: Deck, DiscardPile
draw_card: one card
meld_option: PlayMeld, LayOff, ContinueDiscard
meld_value: string of cards
winner: models.ForeignKey(RummyPlayer.username)

**Comment by ngreenwald89** [comment]
Models have been created, and game moves are logged.

Wins / Losses need to be logged, to be done after GameOver is finished.
GameStats page needs to be created.

**Comment by ngreenwald89** [comment]
Wins / Losses are logged.
Just need to create stats page.

**Comment by ngreenwald89** [comment]
Nat may make stats page.

**Comment by ngreenwald89** [comment]
Game Stats and Move Detail page created.
