### ISSUE TITLE
Tool for security analysis

### ISSUE THREAD

**Issue by iAmHuss** [ngreenwald89/gin_rummy#16]
must use at least one tool to examine your program and fix any vulnerabilities it finds before submitting it. You can choose a dynamic analysis tool (such as OWASP ZAP) or a static analysis tool (such as PMD, FindBugs, or Fortify). It's best to use several tools, preferably of different kinds, since different tools find different things. This tool use should be included in your assurance case, of course. Using and responding to a tool report will not only help you make your program secure, but the process will probably help you understand how to make software more secure in general. Start applying the tool as soon you can; don't wait until the end of the project.

**Comment by ngreenwald89** [comment]
For static analysis, maybe can use a tool like pylint or django-lint
https://chris-lamb.co.uk/projects/django-lint
https://github.com/PyCQA/pylint-django

**Comment by ngreenwald89** [comment]
pylint-django would be better than django-lint. More active project, has many more contributors and recent commits.

**Comment by ngreenwald89** [comment]
using pylint-django
